[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "logger-lib"
version = "0.1.0"
description = "Plug and play logging module"
authors = [{ name = "Gaurav Pandey" }]
dependencies = []